# [Info]
site_name: JUN WANG's Home Page # 左上角标题
site_url: https://wenmnal.github.io
site_author: JUN WANG 
site_description: Jun Wang's Home Page

# [Navigtion]
nav:
  - Home: 
    - index.md
  - Study:
    - Study/index.md # 顶部导航栏的标题
    - Physics: 
      - Formula:
        - Study/Physics/Formula/formula.md
      - Quantum Mechanics: 
        - Study/Physics/Quantum Mechanics/第一章 绪论.md
        - Study/Physics/Quantum Mechanics/第二章 非相对论粒子波函数和 Schrödinger 方程.md
        - Study/Physics/Quantum Mechanics/第三章 形式理论.md
        - Study/Physics/Quantum Mechanics/量子力学复习.md
        - Study/Physics/Quantum Mechanics/附录 A 量子力学问题.md
      - Statistical Physics:
        - Study/Physics/Statistical Physics/Maxwell 关系.md
      - Mathematical Physics:  
        - Study/Physics/Mathematical Physics/Complex Analysis/Formula of Complex Analysis.md
        #- Study/Physics/Mathematical Physics/Group theory/第一章李群和李代数的基本概念.md
        #- Study/Physics/Mathematical Physics/Sadri Hassani Mathematical Physics/Part 0 Mathematical Preliminaries.md
      - Quantum Field Theory:
        - Introduction to Quantum Field Theory:
          - Study/Physics/Quantum Field Theory/Introduction to Quantum Field Theory by peskin/Introductio to Quantum Field Theory Note.md
          - Study/Physics/Quantum Field Theory/Introduction to Quantum Field Theory by peskin/量子场论公式与记号.md 
        - Quantum Field Theory for the Gifted amateur:
          - Study/Physics/Quantum Field Theory/QFTFGA Note/Part I The Universe as a set of harmonic oscillators.md
          - Study/Physics/Quantum Field Theory/QFTFGA Note/Part II Writing down Lagrangians.md
          - Study/Physics/Quantum Field Theory/QFTFGA Note/Part IV Propagators and perturbations.md
      - Thesis:
        - Study/Physics/Thesis/More is different/More_is_Different.md
        - Study/Physics/Thesis/More is different/More Is Different Chinese.md
    - Math: 
      - Algebra: 
        - Study/Math/Algebra/Linear_Algebra_Done_Right.md
  - Me:
    - Self Introduction:
      - Me/Self_Introduction/About_Me.md
# [UI]
## [top]
theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: black # 上方的
      accent: blue # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  font:
    text: Noto Sans Math # 文字字体
    code: Roboto Mono
  features:
    - announce.dismiss
    #- content.action.edit
    #- content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - navigation.tabs # 使用Tab来进行分类
    # - navigation.top # 返回顶部的按钮 在上滑时出现
    # - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    # - navigation.expand # 打开Tab时左侧目录全部展开
    # - search.suggest # 搜索输入一些字母时推荐补全整个单词
    # - search.highlight # 搜索出的文章关键词加入高亮
    # - content.code.copy # 可以通过按钮复制代码
    # - content.action.edit # 点击按钮跳转到编辑页面  需要结合 edit_uri 一起使用
  language: en # 一些提示性的文字会变成中文
## [top-right corner]
repo_url: https://github.com/wenmnal/wenmnal.github.io # 右上角点击跳转的链接
repo_name: wenmnal.github.io # 右上角的名字
## [bottom-left corner]
# copyright: 王俊 CC-BY-4.0 # 左下角的版权声明
## [bottom-right corner]
# extra:
#   social: # icons
#     - icon: fontawesome/brands/github
#       link: https://github.com/wenmnal
#       name: GitHub | wenmnal

# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  # - pymdownx.arithmatex: # latex支持
  #     generic: true
  # - attr_list # 给图片后面添加{width="300"}设置大小
  # - toc:
  #     permalink: true # 固定标题位置为当前位置
  # - pymdownx.highlight: # 代码块高亮
  #      linenums: true # 显示行号
  #      auto_title: true # 显示编程语言名称
  # - pymdownx.superfences # 代码块高亮插件
  # # 支持Markdown文件上方自定义标题标签等
  # - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  # - pymdownx.details # admonition需要
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  #- https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js 
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  #- stylesheets/no-footer.css # 不使用底部的翻页
  - stylesheets/unordered-list-symbols.css # multiplt unordered list symbols
