[site]
title = "Jun Wang"
description = "Personal homepage of a PhD student at the Institute of High Energy Physics, CAS."
favicon = "/favicon.svg"
last_updated = "June 11, 2026"

[author]
name = "Jun Wang"
title = "PhD Student"
institution = "Institute of High Energy Physics, CAS"
avatar = "/Stack.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "junwang@ihep.ac.cn"
location = "Beijing, China"
location_url = "https://maps.google.com/?q=Institute+of+High+Energy+Physics+CAS+Beijing"
location_details = [
  "Institute of High Energy Physics, CAS, Theoretical Physics Division",
  "19B Yuquan Road, Shijingshan District, Beijing, China"
]
# google_scholar = "https://scholar.google.com"
orcid = "https://orcid.org/0000-0002-0508-3349"
github = "https://github.com/wenmnal"
# linkedin = "https://linkedin.com"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = true
locales = ["zh", "en"]
default_locale = "en"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale (but can be switched still, if you want to disable, set "enable=false")
mode = "auto"
fixed_locale = "en"
# If true, PRISM will remember user's language preference in browser's localStorage
persist = true
# Show a language switcher on the top right corner
switcher = true

[i18n.labels]
zh = "中文"
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

# [[navigation]]
# title = "Teaching"
# type = "page"
# target = "teaching"
# href = "/teaching"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "Documents"
type = "page"
target = "doc"
href = "/doc"
# [[navigation]]
# title = "Services"
# type = "page"
# target = "services"
# href = "/services"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
