[[news]]
date = "2026-08"
content = "Third paper accepted 🎉"

[[news]]
date = "2026-03"
content = "Fourth paper completed ✅"

[[news]]
date = "2026-01"
content = "Third paper completed ✅"

[[news]]
date = "2025-10"
content = "Second paper accepted 🎉"

[[news]]
date = "2025-07"
content = "Second paper completed ✅"

[[news]]
date = "2025-04"
content = "First paper accepted 🎉"

[[news]]
date = "2025-03"
content = "First paper completed ✅"

[[news]]
date = "2024-09"
content = "Started coursework at Yanqi Lake campus"
