[site]
title = "王俊"
description = "中国科学院高能物理研究所理论物理学博士生个人主页."
last_updated = "2026年6月11日"

[author]
name = "王俊"
title = "博士研究生"
institution = "中国科学院高能物理研究所"

[social]
email = "junwang@ihep.ac.cn"
location = "北京, 中国"
location_url = "https://uri.amap.com/marker?position=116.251,39.91&name=中国科学院高能物理研究所"
location_details = [
  "中国科学院高能物理研究所,理论物理室",
  "玉泉路 19 号乙, 石景山区, 北京, 中国"
]
orcid = "https://orcid.org/0000-0002-0508-3349"
github = "https://github.com/wenmnal"

[[navigation]]
title = "关于我"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "论文"
type = "page"
target = "publications"
href = "/publications"

# [[navigation]]
# title = "教学"
# type = "page"
# target = "teaching"
# href = "/teaching"

[[navigation]]
title = "奖项"
type = "page"
target = "awards"
href = "/awards"

# [[navigation]]
# title = "服务"
# type = "page"
# target = "services"
# href = "/services"

[[navigation]]
title = "简历"
type = "page"
target = "cv"
href = "/cv"
