# [[news]]
# date = "2025-04"
# content = "第一篇论文被接收 🎉"
[[news]]
date = "2026-08"
content = "第三篇论文被接收 🎉"

[[news]]
date = "2026-03"
content = "第四篇论文完成 ✅"

[[news]]
date = "2026-01"
content = "第三篇论文完成 ✅"

[[news]]
date = "2025-10"
content = "第二篇论文被接收 🎉"

[[news]]
date = "2025-07"
content = "第二篇论文完成 ✅"

[[news]]
date = "2025-04"
content = "第一篇论文被接收 🎉"

[[news]]
date = "2025-03"
content = "第一篇论文完成 ✅"

[[news]]
date = "2024-09"
content = "开始雁栖湖集中教学"
